apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: monitoring
spec:
  serviceName: grafana
  selector:
    matchLabels:
      name: grafana
  replicas: 1
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
      - image: grafana/grafana:5.3.2
        name: grafana
        env:
          - name: GF_AUTH_BASIC_ENABLED
            value: "true"
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: grafana
                key: admin-username
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana
                key: admin-password
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "false"
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
        volumeMounts:
        - name: grafana-config
          mountPath: /var/lib/grafana
  volumeClaimTemplates:
    - metadata:
        name: grafana-config
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Mi